
NAME = client
NAMESV = 
HEADER = 
OBJ = 
CC = 
FLAGS = 
FSANITIZE = 
RM = 
ECHO = 



DEF_COLOR	=	\033[0;39m
ORANGE = 
RED = 
...
#check add colors

SRCCL_FILES = client
SRCSV_FILES = server

SRCCL = 


#CHECK addprefix and addsuffix
