
NAME = client
NAMESV = server
HEADER = minitalk
OBJS = %()
CC = gcc $(CFLAGS)
CFLAGS = -Wall -Werror -Wextra
FSANITIZE = 
RM = rm -f 
ECHO = 



BLACK("\033[0;30m"),    // BLACK
RED("\033[0;31m"),      // RED
GREEN("\033[0;32m"),    // GREEN
YELLOW("\033[0;33m"),   // YELLOW
BLUE("\033[0;34m"),     // BLUE
MAGENTA("\033[0;35m"),  // MAGENTA
CYAN("\033[0;36m"),     // CYAN
WHITE("\033[0;37m"),    // WHITE
#check add colors

SRCCL_FILES = client
SRCSV_FILES = server
SRCCL = 

.c.o:
	$(CC) $(CFLAGS) -I include -c $< -o $(<:.c=.o)


all: $(NAME)

clean:
	$(RM) $(OBJS)
fclean: clean
	$(RM) $(NAME) a.out
re: fclean all

.PHONY: all re clean fclean


#CHECK addprefix and addsuffix